@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "username":"danny",
    "password":"danny",
    "email":"danny@gmail.com",
    "avatarColor":"red",
    "avatarImage":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAACACAMAAADTa0c4AAAAA1BMVEX///+nxBvIAAAAN0lEQVR4nO3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAtwGAgAABEToL+QAAAABJRU5ErkJggg=="
}

